### ISSUE TITLE
Modularize json support

### ISSUE THREAD

**Issue by Jacoby6000** [hmrc/simple-reactivemongo#30]
I think the play json dependency should be pulled out and put in to a seperate project.  This way, people can write drivers for other json libraries. I'd be willing to make a json4s plugin, and I'm sure somebody would appreciate a spray-json plugin as well.

I've almost completely ported the Play-ReactiveMongo plugin to json4s... Only issues remaining have to do with lists and BSONObjectIds. Creating a json4s implementation on this seems like it would be trivial in comparison.

**Comment by duncancrawford** [comment]
Hi @Jacoby6000 if you want to submit a PR then we are always happy to consider improvements
