### ISSUE TITLE
Rename the library

### ISSUE THREAD

**Issue by duncancrawford** [hmrc/simple-reactivemongo#38]
Anything with simple in the name just doesn't seem right to me. It is also not that descriptive. I would like to rename this lib but to what.

The only thing I have thought so far is 'reactive-repository'

Any other thoughts?

**Comment by agilestevesmith** [comment]
reactivemongo-serialiser

**Comment by NTCoding** [comment]
reactivemongo-generic-repository

**Comment by charleskubicek** [comment]
Given it's the repository pattern applied in a reactive fashion over Mongo I'd say:

reactive-mongo-repository.

**Comment by agilestevesmith** [comment]
Final offer: reactivemongo-repository
