### ISSUE TITLE
Consider upgrade to akka-actor:2.4.14

### ISSUE THREAD

**Issue by frgomes** [hmrc/simple-reactivemongo#56]
simple-reactivemongo/project/HmrcBuild.scala defines dependencies from reactivemongo and play like this:
```
    // USING HMRC FORK OF REACTIVEMONGO - https://github.com/hmrc/ReactiveMongo
    val reactiveMongo = "uk.gov.hmrc" %% "reactivemongo" % "0.13.0"

    val playJson = "com.typesafe.play" %% "play-json" % "2.5.12" % "provided"
```

ReactiveMongo, line 131 has a dependency from akka-actor:2.3.6. It should be 2.4.14.
https://github.com/hmrc/ReactiveMongo/blob/master/project/ReactiveMongo.scala

```
val akkaActor = "com.typesafe.akka" %% "akka-actor" % "2.3.6"
```

However, Play defines a transient dependency of akka-actor:2.4.14.

Since SBT chooses the latest version 2.4.14, libraries dependent on 2.3.6 may _potentially_ break.

In Slack I did some analysis employing ``sbt evicted`` and ``sbt dependencyTree`` which found this potential issue.

https://hmrcdigital.slack.com/archives/event-play-upgrade/p1488888417002563

**Comment by beyond-code-github** [comment]
Have posted an update regarding this in slack, however leaving this open for now as we do want to address this when we have time and resource available :+1:

**Comment by colin-lamed** [comment]
Believe this is not applicable now. simple-reactivemongo does not use the fork anymore.
The version of akka used by the current version of reactivemongo is 2.3.13 for 2.11 and 2.5.25 for 2.12:
https://github.com/ReactiveMongo/ReactiveMongo/blob/4202ae10e031bc01b9847f7ec6c4deca7b16a124/project/Dependencies.scala#L24-L25
